# Generated by Django 4.2.6 on 2023-12-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project_img/default.png', null=True, upload_to='project_img'),
        ),
    ]
