# Generated by Django 4.2.6 on 2023-12-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='profile_img/default.png', null=True, upload_to='profile_img'),
        ),
    ]
