# Generated by Django 4.2.6 on 2023-10-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0002_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='person',
            name='password2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
