# Generated by Django 4.2.6 on 2023-12-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0002_remove_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
