# Generated by Django 4.2.6 on 2023-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0003_rename_password_person_password1_person_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
