# Generated by Django 4.2.6 on 2023-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0004_alter_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chosen_group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
