# Generated by Django 4.2.6 on 2023-12-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0005_person_chosen_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='chosen_group',
        ),
    ]
