# Generated by Django 4.2.6 on 2023-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0006_remove_person_chosen_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.CharField(blank=True, choices=[('teacher', 'Учитель'), ('student', 'Ученик'), ('parent', 'Родитель')], max_length=50, null=True),
        ),
    ]
