# Generated by Django 4.2.6 on 2023-12-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('study_project', '0007_person_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
