# Generated by Django 4.2.6 on 2023-10-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0007_person_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_project.class'),
        ),
    ]
