# Generated by Django 4.2.6 on 2023-12-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0008_alter_person_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
    ]
