# Generated by Django 4.2.6 on 2023-10-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0009_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='school_class',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_project.class'),
        ),
    ]
