# Generated by Django 4.2.6 on 2023-10-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_project', '0011_remove_person_school_class_class_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='user',
        ),
        migrations.AddField(
            model_name='person',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_project.class'),
        ),
    ]
